version: "3"

services:
  api-math:
    container_name: go-kit-api-math
    build:
      context: api/math
      dockerfile: docker/dev/Dockerfile
    command: air -c .air.api.toml
    ports:
      - 9000:9000
    env_file:
      - api/math/.env
    volumes:
      - ./api/math:/go/src/app
    working_dir: /go/src/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - go-kit

networks:
  go-kit:
    external: true
